//! Test support for §8.7 item 6 (MC contract v1.3, CQ2-F): the
//! field-equality test `tests/campaign_equality.rs` compiles the
//! simulator's own source next to the port, as `tests/profile_equality.rs`
//! does for the profiles (I-36). The simulator's planner functions are
//! private to its `sim` module, so this script writes a copy of
//! `frontier-sim/src/*.rs` into `OUT_DIR` with three mechanical changes and
//! no change to any expression:
//!
//! 1. visibility: `pub(super)` / `pub(crate)` become `pub`, and the
//!    methods of `sim_campaign.rs` / `sim_mc.rs` (each file is one
//!    `impl Sim` block) and a few named `sim.rs` helpers become `pub`;
//! 2. four probes: `mc_campaign_epoch` becomes a wrapper that calls
//!    `crate::cq_probe::{before, after}` around the original body (renamed
//!    `mc_campaign_epoch_inner`), so the test sees the planner's exact
//!    input and output state; and `mc_campaign_fill` hands its ranked
//!    candidate list to `crate::cq_probe::candidates` right after sorting
//!    it (a read of a local, no change to the list); the rally stay of
//!    `resolve_bell` hands its decision to `crate::cq_probe::rally`; and
//!    each of the two hold-rule assignments names its host to
//!    `crate::cq_probe::hold_rule`;
//! 3. the simulator's own tests are compiled out (`#[cfg(test)]` →
//!    `#[cfg(any())]`) and `//!` becomes `//` (inline modules).
//!
//! The library and the binaries never include the file; only the test
//! does. When the simulator changes, the copy follows and the test
//! re-checks the port.
//!
//! **This script never fails the build** (CQ2-F review): when a source is
//! missing or an anchor line moved (a `cargo fmt` reflow, the doctrine
//! re-tune, a renamed function), the generated file is a single
//! `compile_error!` that only `tests/campaign_equality.rs` includes, so
//! the keeper, the bots and the integration tests that depend on this
//! crate build on whatever the simulator looks like.

use std::path::Path;

/// `frontier-sim/src/main.rs`'s modules (its tests excepted).
const MODULES: &[&str] = &[
    "balance", "c4", "config", "conquest", "k2", "mapmove", "mc", "model", "report", "rng",
    "settle", "sim", "suite",
];

/// `sim.rs` helpers the test calls.
const SIM_HELPERS: &[&str] = &["provinces_near", "prov_at", "travel", "keep_reinforcement"];

fn read(dir: &Path, name: &str) -> Result<String, String> {
    let p = dir.join(name);
    println!("cargo:rerun-if-changed={}", p.display());
    std::fs::read_to_string(&p).map_err(|e| format!("{}: {e}", p.display()))
}

fn common(src: &str) -> String {
    let mut out = String::with_capacity(src.len() + 1024);
    for line in src.lines() {
        let t = line.trim_start();
        let l = if t.starts_with("//!") {
            line.replacen("//!", "//", 1)
        } else if t == "#[cfg(test)]" {
            line.replacen("#[cfg(test)]", "#[cfg(any())]", 1)
        } else {
            line.replace("pub(super) ", "pub ")
                .replace("pub(crate) ", "pub ")
        };
        out.push_str(&l);
        out.push('\n');
    }
    out
}

/// Every 4-space `fn` of a file that is one `impl Sim` block, and its
/// two structs' fields, become `pub`.
fn lift_impl(src: &str) -> String {
    let mut out = String::with_capacity(src.len() + 4096);
    let mut in_struct = false;
    for line in src.lines() {
        let mut l = line.to_string();
        if let Some(rest) = line.strip_prefix("    fn ") {
            l = format!("    pub fn {rest}");
        } else if let Some(rest) = line.strip_prefix("struct ") {
            l = format!("pub struct {rest}");
            in_struct = rest.trim_end().ends_with('{');
        } else if in_struct {
            if line.starts_with('}') {
                in_struct = false;
            } else if line.starts_with("    ") && !line.trim_start().starts_with("//") {
                l = format!("    pub {}", line.trim_start());
            }
        }
        out.push_str(&l);
        out.push('\n');
    }
    out
}

fn generate(dir: &Path) -> Result<String, String> {
    let mut gen = String::new();
    gen.push_str("// @generated by crates/agents/build.rs from frontier-sim/src (see there).\n");
    for m in MODULES {
        let mut body = common(&read(dir, &format!("{m}.rs"))?);
        if *m == "sim" {
            for h in SIM_HELPERS {
                body = body.replace(&format!("    fn {h}("), &format!("    pub fn {h}("));
            }
            let stay = "                                && self.cfg.policy[fac] == crate::mc::Policy::Campaign;\n";
            if body.matches(stay).count() != 1 {
                return Err("the rally stay moved: update build.rs".into());
            }
            body = body.replacen(
                stay,
                &format!("{stay}                            crate::cq_probe::rally(self, b, t, fac, stays);\n"),
                1,
            );
            let campaign = lift_impl(&common(&read(dir, "sim_campaign.rs")?));
            let sig = "    pub fn mc_campaign_epoch(&mut self, b: u32) {\n";
            if !campaign.contains(sig) {
                return Err("mc_campaign_epoch moved: update build.rs".into());
            }
            let campaign = campaign.replacen(
                sig,
                "    pub fn mc_campaign_epoch(&mut self, b: u32) {\n        \
                 crate::cq_probe::before(self, b);\n        \
                 self.mc_campaign_epoch_inner(b);\n        \
                 crate::cq_probe::after(self, b);\n    }\n\n    \
                 pub fn mc_campaign_epoch_inner(&mut self, b: u32) {\n",
                1,
            );
            let sort = "        cands.sort_by(|a, b| b.0.total_cmp(&a.0).then(a.1.cmp(&b.1)));\n";
            if campaign.matches(sort).count() != 1 {
                return Err("the fill's sort moved: update build.rs".into());
            }
            let campaign = campaign.replacen(
                sort,
                &format!("{sort}        crate::cq_probe::candidates(f, b, &cands);\n"),
                1,
            );
            // The hold rule's two assignments (§8.6, A-14): each reports the
            // host it gave a retreat order (a read of `h`, no change).
            let hold = "self.hosts[h as usize].retreat = Some(Self::occ_retreat(total, own));\n";
            if campaign.matches(hold).count() != 2 {
                return Err("the hold rule's assignments moved: update build.rs".into());
            }
            let campaign = campaign.replace(
                hold,
                &format!("{hold}                crate::cq_probe::hold_rule(h);\n"),
            );
            let mcsim = lift_impl(&common(&read(dir, "sim_mc.rs")?));
            let a = "#[path = \"sim_campaign.rs\"]\npub mod campaign;\n";
            let b = "#[path = \"sim_mc.rs\"]\npub mod mcsim;\n";
            if !(body.contains(a) && body.contains(b)) {
                return Err("sim.rs modules moved: update build.rs".into());
            }
            body = body
                .replacen(a, &format!("pub mod campaign {{\n{campaign}}}\n"), 1)
                .replacen(b, &format!("pub mod mcsim {{\n{mcsim}}}\n"), 1);
        }
        gen.push_str(&format!(
            "#[allow(warnings, clippy::all, clippy::pedantic, unused)]\npub mod {m} {{\n{body}}}\n"
        ));
    }
    Ok(gen)
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    let dir = Path::new(&manifest).join("../../../frontier-sim/src");
    let out_dir = std::env::var("OUT_DIR").unwrap_or_default();
    let out = Path::new(&out_dir).join("frontier_sim_lifted.rs");
    let gen = match generate(&dir) {
        Ok(g) => g,
        Err(e) => format!("compile_error!({e:?});\n"),
    };
    // Only written when it changed: a rerun for an unrelated simulator edit
    // leaves the file (and what is built from it) alone.
    if std::fs::read_to_string(&out).ok().as_deref() != Some(gen.as_str()) {
        if let Err(e) = std::fs::write(&out, &gen) {
            println!(
                "cargo:warning=agents/build.rs: cannot write {}: {e}",
                out.display()
            );
        }
    }
}
